default: &default
  adapter: mysql2
  pool: 5
  username: root
  password: 
  port: <%= ENV['MYSQL_PORT'] || 3306 %>

test:
  <<: *default
  database: greentestmini_test

development:
  <<: *default
  database: greentestmini

production:
  <<: *default
  database: greentestmini
